version: "3.4"

services:
  classical_exps:
    container_name: jonas_classical_exps_dyscal_gpu1
    image: classical_exps
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - GITHUB_USER=${GITHUB_USER}
        - GITHUB_TOKEN=${GITHUB_TOKEN}
    volumes:
      - .:/project
    env_file: .env
    runtime: nvidia
    environment:
      - NVIDIA_VISIBLE_DEVICES=1